kind: ethereum/contract
name: NftSale
network:
source:
  address: ""
  abi: NftSale
  startBlock:
mapping:
  kind: ethereum/events
  apiVersion: 0.0.3
  language: wasm/assemblyscript
  entities:
    - Order
  abis:
    - name: NftSale
      file: ./abis/NftSale.json
  eventHandlers:
    - event: SetOrder(indexed address,uint256,uint256,address,address,address,string)
      handler: handleSetOrder
    - event: FillOrder(indexed address,uint256,address,address,address,uint256)
      handler: handleFillOrder
    - event: CloseOrder(address,uint256)
      handler: handleCloseOrder
  file: ./src/nft-sale-mappings.ts
